### PR TITLE
Update bingRewards.py

### PR DESCRIPTION
**Pull request by specu**
Fix for "ValueError: substring not found" that started on May 31

### CODE REVIEW

**Comment by amayer5125** [comment]
Can you please bump the version and date in main.py and add your change to version.txt?

**Comment by specu** [comment]
@amayer5125 1 sec. it will probably be a new pull request.

**Comment by amayer5125** [comment]
Still need to add your change to version.txt and update the version there.

**Comment by specu** [comment]
@amayer5125 apparently it all went into this pull request. I think I got everything(?)

**Comment by amayer5125** [comment]
For future reference if you don't have any branches based off the one you are pushing you can do something like this:
```bash
git add file.txt
git commit --amend
git  push -f origin branch-name-here
```
This will amend the last commit with any staged files. You then need to force push (`-f`) because the commit hash has changed. That way you only have 1 commit with all the changes.

**Comment by specu** [comment]
Thank you.

**Pull request merged**
