### PR TITLE
Fix .trim() Bug

### PR DESCRIPTION
**Pull request by amayer5125**
Should be .strip()

### CODE REVIEW

**Comment by amayer5125** [comment]
@sealemar can you pull this. I guess we both forgot it should be `.strip()` instead of `.trim()`

**Comment by amayer5125** [comment]
@sealemar did you have a chance to look at this yet?

**Comment by amayer5125** [comment]
@sealemar Thanks :)

**Comment by sealemar** [comment]
@amayer5125 thank you :) I didn't even pay attention to the function name

**Pull request merged**
