### PR TITLE
Add Warp speed quiz to fix error 400

### PR DESCRIPTION
**Pull request by sinkillerj**

### CODE REVIEW

**Comment by amayer5125** [comment]
I dont want to be too picky here but can you move `WARPSPEED_QUIZ)` to the next line so the last line in `ALL = (` isnt so long?
If you do that I will merge.

**Comment by specu** [comment]
there's discussion on it in #238

**Comment by FunkyEssence** [comment]
Before we keep adding individual quizzes, we should use a regex method to pass all quizzes.

**Comment by amayer5125** [comment]
This is being implemented here #244

**Pull request closed without merging**
