### PR TITLE
add multiprocessing feature

### PR DESCRIPTION
**Pull request by kenneyhe**
Add multiprocess run wrapper to run n process with n accounts.  Increase performance by increasing number of concurrent http requests.

``` bash
# same as main.py if running with one process
python mpmain.py 1 ../mp/config.xml
Live - erwer34@qq.com
No RegEx matches found for this search and earn
Result 1/2:
-----------
name        : Search and earn
url         : http://www.bing.com/explore/rewards?FORM=MA1377&wt.mc_id=MA1377
description : For a limited time you're earning free credits. Activate your account to claim them.
   Error    :   true
   Message  : No RegEx matches found for this search and earn
   Action   : search

Result 2/2:
-----------
name        : Join Now
url         : http://www.bing.com/explore/rewards?FORM=MA1377&wt.mc_id=MA1377&PUBL=BINGCOM&CREA=MA1377
description : Use Bing. Join Bing Rewards to start earning credits toward free rewards.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn
```

### CODE REVIEW

**Comment by kenneyhe** [comment]
Does any one want PR for Function as a service feature together with multiprocess? I have that as well...

**Comment by zengfu94** [comment]
have fun getting banned, you posted your email.

**Comment by specu** [comment]
the other thing that people post, which is probably worse is br_id

**Comment by zengfu94** [comment]
ironically it's a post about wanting to merge something to increase ban chances. maybe he's a double agent.

**Comment by kenneyhe** [comment]
I have cashed in and has not ban with this code for last ~30 days

**Comment by kenneyhe** [comment]
I do not use my email. LOL

**Comment by amayer5125** [comment]
I am not sure we want a multiprocessing feature. I think tallying points low and slow is probably the best way. Does anyone else have an opinion on this?

**Comment by specu** [comment]
@amayer5125 I'm with you on this one.

**Comment by kenneyhe** [comment]
I will send another PR with dockerfile

**Comment by elisiano** [comment]
@kenneyhe #292 already adds a Dockerfile

**Pull request closed without merging**
