### PR TITLE
Support for quizzes

### PR DESCRIPTION
**Pull request by specu**
This does all quizzes as well as  "Daily Poll" and "Test your smarts", which work the same way as quizzes.
This collides a bit with 392, which has a lot of changes, I'm not sure if all of those are necessary.

### CODE REVIEW

**Comment by specu** [comment]
@amayer5125 All done and tested  
if anyone wants to try this patch, the following worked for me:
wget https://github.com/sealemar/BingRewards/pull/393.patch
patch -p1 < 393.patch

**Comment by LYHTSPD** [comment]
I patched with 393 and ran it on all my accounts.  It seems to work for the most part, but on one account that I keep current for the streak, it missed a Daily Poll that was not in the daily set, and on another account that I don't even look at, it missed a Test Your Smarts and a Daily Poll that was not in the Daily Set.  Seems like it is missing the older Polls and Test Your Smarts, but it picked up every old turbo/supersonic/warp speed quiz.

**Comment by LYHTSPD** [comment]
So there is a Daily Set of 3 things to do, usually a Daily Poll, a single click event, and a Quiz of some sort.  On all the accounts, it completed the Daily Set correctly.  On some accounts, it completed all the quizzes, even ones that were several days old, but it did not complete the Daily Polls or Test Your Smarts items that were not in the Daily Set.
 Does that make sense?

**Comment by mattohm** [comment]
I'm seeing the same thing.  Log shows it completed, but dashboard shows it hasn't.

Running activity: Daily Poll

2018-09-06 11:25:33.2 - 10/10 - Activity: Daily Poll

**Comment by specu** [comment]
@mattohm in that log, in the results section, is there a message for Daily Poll?

**Comment by mattohm** [comment]
It appears I'm too lazy to update my paths in the config.  I just have the output from running, no logs.

**Comment by specu** [comment]
@mattohm @LYHTSPD so the situation is @amayer5125 is the sole admin here and doesnt even run the script anymore. Hence I guess what is mostly useful here is do you think this patch be applied or not based on your testing?

**Comment by mattohm** [comment]
Yes.

**Comment by LYHTSPD** [comment]
I think it should be applied, but further development needs to be done to take care of the old/missed activities.

**Comment by specu** [comment]
@LYHTSPD thank you. I suspect the old activities are missed by the dashboard parser altogether - if they're not in the log then that's definitely the case.

**Comment by specu** [comment]
@LYHTSPD @mattohm could you make sure that in pkg/bingDashboardParser.py where it says
if reward.progressMax == 10 and reward.progressCurrent != 10
you have it as:
if reward.progressMax == 10 and reward.progressCurrent != 10 and reward.tp is None:
?
If the patch wasnt applied completely, that would cause the issue you're seeing.

**Comment by mattohm** [comment]
if reward.progressMax == 10 and reward.progressCurrent != 10 and reward.tp is None:
        reward.tp = Reward.Type.RE_EARN_CREDITS

**Comment by LYHTSPD** [comment]
Mine is the same as @mattohm

**Comment by specu** [comment]
2 of my accounts got 2 times Daily Poll today. That might be the reason.

**Pull request merged**
