### PR TITLE
Pass all quizzes - Fix #238/#240

### LINKED ISSUE #238: New 400 Error
The server couldn't fulfill the request.
Error code:  400

### PR DESCRIPTION
**Pull request by FunkyEssence**
Added regex to pass all quizzes (with the word "quiz" in the title). I tested this on one of my accounts and no 400 error showed. Please test and let me know if you encounter any issues.

### CODE REVIEW

**Comment by specu** [comment]
all quizes so far had the word quiz as a last word after a space so I think ".* quiz$" is better in case there's an activity that has that word in the middle or something:
https://github.com/sealemar/BingRewards/issues/238#issuecomment-302482085

**Comment by FunkyEssence** [comment]
Is the space needed between * and quiz?  A "." should cover the space.

**Comment by specu** [comment]
For all the quizzes mentioned so far there was always a space there. I'm trying to cover precisely all the problematic instances so far. So I would be for leaving the regex as is with the space.
I've also tested the second patch I posted - this shows which activity was tried before a catastrophic error occurred.

**Comment by FunkyEssence** [comment]
Only problem I see with ".* quiz$" is that it wont work if the work quiz is in the middle for future quizzes, and there has to be a space before "quiz". E.g. Coffee quiz break OR Quiz coffee break.

I've updated it to:
`re.compile(".*quiz.*", flags=re.IGNORECASE)`

This would work for all the quizzes (and potential future naming conventions):
- Coffee break quiz
- Coffee quiz break   (works if "quiz" is in the middle of the name)
- Coffee Break Quiz  (ignore case will allow this to work if Bing capitalizes the "q" in Quiz)
- Quiz coffee break   (works if "quiz" is first)

Thoughts?

**Comment by specu** [comment]
I'm fairly junior here, so the purpose of ".* quiz$" was to specifically accomodate all the past quizzes and nothing more. So in case a 10 point activity comes along that has words like quizmaster or quizzed in it, that activity would be still hit. As far as I know there were never quizzes in the past that did not end with space quiz.

**Comment by FunkyEssence** [comment]
Totally agree with you. The ".* quiz$" works for the all current quizzes and past ones that have been done. This would be more of a future proof syntax I suppose.

**Comment by specu** [comment]
it's not a big deal anyway. we'll tweak it as they throw things at us in future.

**Comment by amayer5125** [comment]
@FunkyEssence I made comments on your code the day you posted it. I didnt know there was a new system in place where I had to hit "start review" in order for them to show up. Sorry for the delay. If you make the changes I requested I will merge them.

**Comment by FunkyEssence** [comment]
@amayer5125 I added the requested changes but have not been able to test today as all my accounts have processed already.

**Comment by specu** [comment]
this is getting pretty messy. i thought it was all done last week.

**Comment by FunkyEssence** [comment]
@amayer5125 I just tested the changes and the accounts are running without the 400 error. Looks like the changes you requested work as well.

**Pull request merged**
