### PR TITLE
Bugfix (Temporary account ban)

### PR DESCRIPTION
**Pull request by HmmU**
Fixed: BingAccountError: Temporary account ban: User was not successfully signed in

### CODE REVIEW

**Comment by peterdimou** [comment]
Tested this change, can verify that I no longer get the temporary account ban error.

**Comment by msea1** [comment]
Can also verify change fixes issues for me.

**Comment by jgkamat** [comment]
+1, this works for me

**Comment by yaroslav-naidyon** [comment]
@HmmU Works like a charm. Very much appreciated.

**Comment by amayer5125** [comment]
Should we future proof this a little better and grab the url from the <form> tag?

**Comment by amayer5125** [comment]
Something like this should work.
Line 246-268 (replacing 246-266):
```python
# get auth form url and contents
authForm = re.search(r"<form.+action=\"([^\"]+)\".*?>(.+)?</form>", page)
if authForm == None:
    filename = helpers.dumpErrorPage(page)
    raise AuthenticationError("Could not find login form:\ncheck " + filename + " file for more information")

parser = HTMLFormInputsParser()
parser.feed(authForm.group(2).decode("utf-8"))
parser.close()
postFields = urllib.urlencode(parser.inputs)

# finish passing authentication

url = authForm.group(1)
request = urllib2.Request(url, postFields, self.httpHeaders)
request.add_header("Origin", "https://login.live.com")

with self.opener.open(request) as response:
    page = helpers.getResponseBody(response)

url = bingCommon.BING_URL
request = urllib2.Request(url, postFields, self.httpHeaders)
request.add_header("Referer", authForm.group(1))
```

**Comment by amayer5125** [comment]
Also we will need to update the version number in **main.py** and update **version.txt**

**Comment by pavanpalaksha** [comment]
Pretty new to GIT. How do I apply these pull request to my project? For now, I simply viewed the diff and changed it manually in my project.

**Comment by PlasmaPower** [comment]
@pavanpalaksha in the future you can do `git pull https://github.com/HmmU/BingRewards.git patch-2` I think

**Comment by pavanpalaksha** [comment]
@PlasmaPower git pull https://github.com/HmmU/BingRewards.git applied the patches I was looking for. Thanks for the suggestion.

**Comment by amayer5125** [comment]
@HmmU now you just need change `SCRIPT_VERSION` to 3.14.2. Update the `SCRIPT_DATE`. And add your commit message to **version.txt**. Just copy the format there and say something like "Fix bingAuth url error"

**Comment by HmmU** [comment]
@amayer5125 Thanks for the help!
Can I add these changes to this pull request or do I need to make a new one?

**Comment by amayer5125** [comment]
@HmmU You should add them to this pull request.

**Comment by amayer5125** [comment]
@sealemar This is good to merge.

**Comment by lyleRpalagar** [comment]
@HmmU Works  for me thank you!

**Pull request merged**
