### PR TITLE
Fixed for Canada and added Windows Scripts

### PR DESCRIPTION
**Pull request by Dreded**
Hey guys.. fixed this so it works for my Canadian account(apparently Canadian site has bad grammar lol) and also made some .bat files for logging and output etc for windows as bash scripts are a pain to get working under windows(although quite possible)

also added a windows example config file(has batch files instead of bash scripts and comments out mail scripts)

and also made a unified script for logging and a unified example config

### CODE REVIEW

**Comment by Dreded** [comment]
realised you definately wouldnt want to merge canadian changes lol...

**Comment by aliasfoxkde** [comment]
@Dreded I'm curious to test it later, but do you by chance know what it does if "points." was changed to "points" and tried for US? And do we know if that fix works for any other region? Thanks

**Comment by godlessfather** [comment]
@aliasfoxkde it fails with "ValueError: substring not found" in the US.

**Comment by aliasfoxkde** [comment]
@godlessfather I just tried it on my phone and it works fine, maybe this was a bug that existed prior to changes made recently? Thanks

**Comment by godlessfather** [comment]
I ran it a few times since and see that it does work properly. I got the substring error occasionally, but it's running properly now.

**Comment by Dreded** [comment]
if it starts without error then it will be fine.. the error comes up right away..

I would think it would error out but it could be replaced with this...
                try:
                    rewardProgressMax = int(rDscSplit[rDscSplit.index('points.')-1])
                except ValueError: #probably canada so try without period
                    rewardProgressMax = int(rDscSplit[rDscSplit.index('points')-1])

**Comment by aliasfoxkde** [comment]
I had the issue come up once out of about 10 time last night, and afterwards the script did a retry a few seconds later and continued on. I don't think it's a problem.

**Pull request closed without merging**
